name: Build Windows x64 Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.19'
        
    - name: Set CUDA and PyTorch versions
      run: |
          echo "MATRIX_CUDA_VERSION=$(echo 11.8.0 | awk -F \. {'print $1 $2'})" >> $GITHUB_ENV
          echo "MATRIX_TORCH_VERSION=$(echo 2.3.1 | awk -F \. {'print $1 "." $2'})" >> $GITHUB_ENV

          
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel  numpy scikit-build-core>=0.4.3 cibuildwheel==2.19.2 lit

    - name: Install C++ build tools
      run: |
        choco install visualstudio2019-workload-vctools -y

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
        
    - uses: actions/upload-artifact@v4
      with: 
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
        
    - name: Upload wheels to GitHub Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wheelhouse/*.whl
        asset_name: $(basename ./wheelhouse/*.whl)
        asset_content_type: application/zip
